### ISSUE TITLE
Firefox can't play video: "Cannot play media. No decoders for requested formats"

### ISSUE THREAD

**Issue by kb173** [FH-Technikum-Wien/ASE-AwesomeTimelapse#18] opened 2021-01-07 15:00 UTC
Firefox doesn't render the output video with the error "Cannot play media. No decoders for requested formats".

Could be due to https://stackoverflow.com/questions/65334051/cannot-play-media-no-decoders-for-requested-formats-on-popular-big-buck-bunny, but the change noted at https://stackoverflow.com/questions/8616855/how-to-output-fragmented-mp4-with-ffmpeg didn't solve it...

**Comment by DavidPgl** [comment] 2021-01-07 18:14
Caused by two reasons:
- Incompatible pixel formats
- Firefox not supporting lossless videos generated with `ffmpeg -crf 0`

FFMPEG's  default pixel format is `yuv444p` which is not compatible with Firefox (and possible other browsers):
https://stackoverflow.com/questions/21184014/ffmpeg-converted-mp4-file-does-not-play-in-firefox-and-chrome

Setting CRF to 1 will be nearly lossless and allows playing the video directly inside Firefox.

**Comment by DavidPgl** [comment] 2021-01-07 18:20
Fixed with #19

**Closed as completed by DavidPgl** 2021-01-07 18:20 UTC
